services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: corehub-backend
    restart: unless-stopped
    ports:
      - "3005:3005"
    networks:
      - core-network
    # Monta il socket Docker per permettere di controllare i container
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NODE_ENV: production

  # Frontend Dashboard
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: corehub-frontend
    restart: unless-stopped
    ports:
      - "3004:3004"
    depends_on:
      - backend
    networks:
      - core-network
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3005/api

networks:
  core-network:
    external: true
    name: core-network
